server:
      port:
          contatos: 8081
          discovery: 8761
      name:
          contatos: sta-contatos

spring:
      jpa.database: POSTGRESQL
      datasource:
                url: "jdbc:postgresql://localhost:5433/sta"
                username: postgres
                password: 123456
